<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HotelHomePage"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="13.417">
  <properties />
            <testcase name="searchHotelInOverseasTrain" time="13.417" classname="test.apptest.hotel.SearchHotelInOverseasTrain">
                <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index: 1, Size: 1"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  java.util.ArrayList.rangeCheck(ArrayList.java:653)
  java.util.ArrayList.get(ArrayList.java:429)
  test.apptest.hotel.SearchHotelInOverseasTrain.searchHotelInOverseasTrain(SearchHotelInOverseasTrain.java:58)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:182)
  org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
